#pragma once

/*
 *  UUID 8d9fee29-fd4c-4b65-a45d-a72a85827ce6 was generated by the uuidgen utility
 *  The last two digits (0x7c, 0xe6) were set to 0x00,0x00.
 *   8d9fee29-fd4c-4b65-a45d-a72a85820000
 *  This string was reversed to form a byte array to conform to
 *  Zephyr's BLE API specifications.
 *   000082852aa7-5da4-654b-4cfd-29ee9f8d
 *
 *  UUID Base (common part) are the last 14 bytes of UUID.
 *  The first two bytes will be Service or Characteristic unique values.
 *  This is similar to the UUID16-type UUIDs specified by the BT SIG.
*/

#define RTLS_UUID_BASE 0x82,0x85,0x2a,0xa7,0x5d,0xa4,0x65,0x4b,0x4c,0xfd,0x29,0xee,0x9f,0x8d

#define RTLS_UUID_SERVICE 0x00,0x04

#define BT_UUID_RTLS_SERVICE \
    BT_UUID_DECLARE_128(RTLS_UUID_SERVICE, RTLS_UUID_BASE)

#define RTLS_UUID_DEVICE_ROLE 0x01,0x04

#define BT_UUID_RTLS_DEVICE_ROLE \
    BT_UUID_DECLARE_128(RTLS_UUID_DEVICE_ROLE, RTLS_UUID_BASE)
